import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || undefined })
await fs.mkdir('artifacts', { recursive: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const wallet = () => page.evaluate(() => JSON.parse(localStorage.getItem('perkify.wallet.v1')))
const dialog = () => page.getByRole('dialog')
await page.goto('http://127.0.0.1:5173/')
await page.getByRole('heading', { name: 'A little more rewarding, Alex.' }).waitFor()
await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true, animations: 'disabled' })

// Real CRUD and persistence, including balance arithmetic and overdraft rejection.
await page.getByRole('button', { name: 'Add a perk', exact: true }).click()
await page.getByRole('button', { name: 'Rewards card Memberships' }).click()
await dialog().getByLabel('Program name').fill('Test Coffee Club')
await dialog().getByLabel('Points balance').fill('100')
await dialog().getByLabel('Estimated cash value').fill('20')
await dialog().getByLabel('Member number').fill('TEST-1234')
await dialog().getByRole('button', { name: 'Add to my wallet' }).click()
assert.equal((await wallet()).cards.find(c => c.name === 'Test Coffee Club').points, 100)
await page.reload()
await page.getByRole('navigation').getByRole('button', { name: 'My wallet', exact: true }).click()
await page.getByLabel('Search perks').fill('Test Coffee')
await page.locator('.reward-card').filter({ hasText: 'Test Coffee Club' }).click()
await dialog().getByRole('button', { name: 'Edit details' }).click()
await dialog().getByLabel('Program name').fill('Test Coffee Updated')
await dialog().getByRole('button', { name: 'Save changes' }).click()
await page.getByRole('button', { name: 'Update points', exact: true }).click()
await dialog().getByLabel('Points to earn').fill('50')
await dialog().getByRole('button', { name: 'Update balance' }).click()
let card = (await wallet()).cards.find(c => c.name === 'Test Coffee Updated')
assert.equal(card.points, 150)
assert.equal(card.value, 30)
await page.getByRole('button', { name: 'Update points', exact: true }).click()
await dialog().getByRole('button', { name: 'Redeem points', exact: true }).click()
await dialog().getByLabel('Points to redeem').fill('151')
await dialog().getByRole('button', { name: 'Update balance' }).click()
await dialog().getByRole('alert').waitFor()
assert.equal((await wallet()).cards.find(c => c.id === card.id).points, 150)
await dialog().getByLabel('Points to redeem').fill('25')
await dialog().getByRole('button', { name: 'Update balance' }).click()
card = (await wallet()).cards.find(c => c.id === card.id)
assert.equal(card.points, 125)
assert.equal(card.value, 25)

// Voucher creation, redemption, and history.
await page.getByRole('navigation').getByRole('button', { name: /^Vouchers/ }).click()
await page.getByRole('button', { name: 'Add a perk', exact: true }).click()
await dialog().getByLabel('Voucher title').fill('Test voucher')
await dialog().getByLabel('Brand or store').fill('Test Store')
await dialog().getByLabel('Voucher value').fill('10')
await dialog().getByLabel('Voucher code').fill('TEST10')
await dialog().getByRole('button', { name: 'Add to my wallet' }).click()
await page.locator('.voucher-tile').filter({ hasText: 'Test Store' }).getByRole('button', { name: 'Use voucher' }).click()
await dialog().getByRole('button', { name: 'Mark as redeemed' }).click()
await dialog().getByRole('button', { name: 'Yes, mark as redeemed' }).click()
assert.equal((await wallet()).vouchers.find(v => v.brand === 'Test Store').redeemed, true)
await page.getByRole('button', { name: 'Redeemed', exact: true }).click()
assert.equal(await page.locator('.voucher-tile').filter({ hasText: 'Test Store' }).count(), 1)
await page.getByRole('navigation').getByRole('button', { name: 'Activity', exact: true }).click()
await page.getByLabel('Search activity').fill('Test')
assert.equal(await page.locator('.activity-row').count(), 5)

// Remove only the requested card; keep the activity history.
await page.getByRole('navigation').getByRole('button', { name: 'My wallet', exact: true }).click()
await page.locator('.reward-card').filter({ hasText: 'Test Coffee Updated' }).click()
await dialog().getByRole('button', { name: 'Remove perk' }).click()
await dialog().getByRole('button', { name: 'Remove perk', exact: true }).click()
assert.equal((await wallet()).cards.some(c => c.id === card.id), false)

// Backup round-trip, malformed import, and destructive-action cancellation.
await page.getByRole('button', { name: 'Settings', exact: true }).click()
await page.getByLabel('Your name').fill('Jamie')
const downloadPromise = page.waitForEvent('download')
await page.getByRole('button', { name: 'Export backup' }).click()
const download = await downloadPromise
await download.saveAs('artifacts/test-backup.json')
const backup = JSON.parse(await fs.readFile('artifacts/test-backup.json', 'utf8'))
assert.equal(backup.settings.name, 'Jamie')
await page.getByRole('button', { name: 'Clear wallet', exact: true }).click()
await dialog().getByRole('button', { name: 'Cancel', exact: true }).click()
assert.equal((await wallet()).cards.length, 4)
await page.getByRole('button', { name: 'Clear wallet', exact: true }).click()
await dialog().getByRole('button', { name: 'Clear wallet', exact: true }).click()
assert.equal((await wallet()).cards.length, 0)
await page.locator('input[type=file]').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{}') })
await page.getByRole('status').filter({ hasText: 'valid Perkify backup' }).waitFor()
assert.equal((await wallet()).cards.length, 0)
await page.locator('input[type=file]').setInputFiles('artifacts/test-backup.json')
await dialog().getByRole('button', { name: 'Restore backup', exact: true }).click()
await page.reload()
assert.equal((await wallet()).cards.length, 4)
await page.getByRole('heading', { name: 'A little more rewarding, Jamie.' }).waitFor()

// Expiry exclusions and mobile layout with isolated sample data.
const { seedData, dateIn } = await import('./src/data.js')
const expired = seedData()
expired.vouchers[0].expiry = dateIn(-1)
expired.cards[0].expiry = dateIn(-1)
await page.evaluate(value => localStorage.setItem('perkify.wallet.v1', JSON.stringify(value)), expired)
await page.reload()
await page.getByRole('navigation').getByRole('button', { name: /^Vouchers/ }).click()
await page.getByRole('button', { name: 'Expired', exact: true }).click()
await page.getByRole('button', { name: 'View details' }).click()
assert.equal(await dialog().getByRole('button', { name: 'Mark as redeemed' }).count(), 0)
await page.keyboard.press('Escape')
assert.equal(await dialog().count(), 0)
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.setViewportSize({ width: 390, height: 844 })
await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true, animations: 'disabled' })
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
await page.getByRole('button', { name: 'Open navigation' }).click()
await page.getByRole('navigation').getByRole('button', { name: /^Vouchers/ }).click()
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
await page.getByRole('button', { name: 'Add a perk', exact: true }).click()
await page.screenshot({ path: 'artifacts/mobile-form.png', fullPage: true, animations: 'disabled' })
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
assert.deepEqual(errors, [])
await browser.close()
console.log('PASS: card CRUD, persistence, point arithmetic, overdraft prevention, voucher redemption, activity, backup/restore, invalid import, expiry rules, mobile layout, and no browser errors.')

